version: '3'
services:
  nginx:
    container_name: pid-nginx
    image: nginx:latest
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - $PWD/web.conf:/etc/nginx/conf.d/web.conf
      - $PWD:/code
  php:
    container_name: pid-php
    image: php:7.3-fpm
    volumes:
      - $PWD:/code
  mysql:
    container_name: pid-mysql
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  adminer:
    container_name: pid_adminer
    image: adminer
    restart: always
    ports:
      - 8888:8080

